# Generated by Django 3.2.19 on 2023-06-21 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите значение цвета в HEX! Пример:#49B64E', regex='^#[A-Fa-f0-9]{6}$')], verbose_name='HEX цвет'),
        ),
    ]
